<?xml version="1.0" encoding="utf-8"?>
<!--
  Copyright (c) 2026 Contributors to the Eclipse Foundation.

  This program and the accompanying materials are made
  available under the terms of the Eclipse Public License 2.0
  which is available at https://www.eclipse.org/legal/epl-2.0/
  SPDX-License-Identifier: EPL-2.0

  Contributors:
-->
<!--
  Generates src/main/resources/docbook/links/osgi-spec-index.xml, the index
  that the html goal uses to link to chapters of other specifications. It is
  run once per published release against the DocBook sources of the legacy
  build (https://github.com/osgi/osgi, osgi.specs/docbook), see the README.

  The books parameter is a space separated list of path=uri pairs, where path
  is the location of the book under the external link base URL and uri is the
  book.xml of that release. Earlier books take precedence for ids that appear
  in more than one book.
-->
<xsl:stylesheet
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:d="http://docbook.org/ns/docbook"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns="urn:org.osgi:docbook:links"
  exclude-result-prefixes="xs d xi"
  version="3.0">

<!-- Line breaks are written explicitly: Saxon-HE indents by 3 and wraps
     long attribute lists, which does not match .editorconfig -->
<xsl:output method="xml" indent="no" encoding="UTF-8"/>

<xsl:param name="books" as="xs:string" required="yes"/>

<xsl:template name="xsl:initial-template">
  <xsl:comment>
  Copyright (c) 2026 Contributors to the Eclipse Foundation.

  This program and the accompanying materials are made
  available under the terms of the Eclipse Public License 2.0
  which is available at https://www.eclipse.org/legal/epl-2.0/
  SPDX-License-Identifier: EPL-2.0

  Contributors:
</xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <xsl:comment> Generated by src/tools/link-index.xsl, do not edit. See the README. </xsl:comment>
  <xsl:text>&#10;</xsl:text>
  <index>
    <xsl:for-each select="tokenize(normalize-space($books), ' ')">
      <xsl:variable name="path" select="substring-before(., '=')"/>
      <xsl:variable name="book" select="doc(substring-after(., '='))"/>
      <xsl:text>&#10;  </xsl:text>
      <book path="{$path}">
        <!-- Prefaces are named by dbhtml PIs, so only these chunks are linked -->
        <xsl:for-each select="$book/d:book/xi:include">
          <xsl:variable name="chunk" select="doc(resolve-uri(@href, base-uri(.)))/(d:chapter | d:appendix)"/>
          <xsl:if test="$chunk/@xml:id">
            <xsl:call-template name="chunk">
              <xsl:with-param name="chunk" select="$chunk"/>
            </xsl:call-template>
          </xsl:if>
        </xsl:for-each>
        <xsl:text>&#10;  </xsl:text>
      </book>
    </xsl:for-each>
    <xsl:text>&#10;</xsl:text>
  </index>
  <xsl:text>&#10;</xsl:text>
</xsl:template>

<xsl:template name="chunk">
  <xsl:param name="chunk" as="element()"/>
  <xsl:variable name="file" select="concat($chunk/@xml:id, '.html')"/>
  <xsl:for-each select="$chunk/descendant-or-self::*[@xml:id][d:title | d:info/d:title]">
    <xsl:text>&#10;    </xsl:text>
    <target id="{@xml:id}" file="{$file}" title="{normalize-space((d:title | d:info/d:title)[1])}">
      <xsl:variable name="label">
        <xsl:call-template name="label">
          <xsl:with-param name="chunk" select="$chunk"/>
        </xsl:call-template>
      </xsl:variable>
      <xsl:if test="string($label)">
        <xsl:attribute name="label" select="$label"/>
      </xsl:if>
    </target>
  </xsl:for-each>
  <!-- The package ids come from the generated javadoc, which is not in the sources -->
  <xsl:for-each select="$chunk//xi:include[contains(@href, 'generated/javadoc/docbook/')]">
    <xsl:variable name="name" select="replace(tokenize(@href, '/')[last()], '\.xml$', '')"/>
    <xsl:if test="not(ends-with($name, '-ddf'))">
      <xsl:text>&#10;    </xsl:text>
      <package name="{$name}" file="{$file}"/>
    </xsl:if>
  </xsl:for-each>
</xsl:template>

<!-- The number DocBook gives a chapter or section (section.autolabel) -->
<xsl:template name="label">
  <xsl:param name="chunk" as="element()"/>
  <xsl:choose>
    <xsl:when test=". is $chunk">
      <xsl:value-of select="@label"/>
    </xsl:when>
    <xsl:when test="self::d:section and $chunk/@label">
      <xsl:value-of select="string-join(($chunk/@label,
          ancestor-or-self::d:section/string(count(preceding-sibling::d:section) + 1)), '.')"/>
    </xsl:when>
  </xsl:choose>
</xsl:template>

</xsl:stylesheet>
