<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.eclipse.osgi-technology.build.tools.maven</groupId>
    <artifactId>maven-plugins</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <artifactId>osgi-docbook-maven-plugin</artifactId>
  <packaging>maven-plugin</packaging>
  <name>Eclipse OSGi Technology Dockbook Maven Plugin</name>
  <description>A Maven Plugin used to generate OSGi specification chapters from
    docbook</description>

  <properties>
    <saxon.version>13.0</saxon.version>
    <fop.version>2.11</fop.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>net.sf.saxon</groupId>
      <artifactId>Saxon-HE</artifactId>
      <version>${saxon.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>fop</artifactId>
      <version>${fop.version}</version>
      <exclusions>
        <exclusion>
          <groupId>xml-apis</groupId>
          <artifactId>xml-apis</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.17</version>
      <scope>test</scope>
    </dependency>
    <!-- Used in the simple test project-->
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.annotation.versioning</artifactId>
      <version>1.1.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
